# Generated by Django 4.1.4 on 2023-02-10 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('shop_id', models.IntegerField()),
                ('no_of_items', models.IntegerField()),
                ('image', models.ImageField(upload_to='images')),
                ('category', models.CharField(choices=[('E', 'Edible'), ('St', 'Stationary'), ('S', 'Sports'), ('E', 'Electronics'), ('L', 'Lifestyles')], default='Edible', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Shopkeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopkeeper_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('shop_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('shop_id', models.IntegerField()),
                ('items_purchased', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('A', 'Approved'), ('W', 'Waiting'), ('D', 'Denied')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(help_text='Enter your password', max_length=200, unique=True)),
                ('is_shopkeeper', models.BooleanField(default='yes')),
                ('is_customer', models.BooleanField(default='Yes')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.IntegerField()),
                ('status', models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='Open', max_length=2)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images')),
                ('area_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.area')),
                ('shopkeeper_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.shopkeeper')),
            ],
        ),
    ]
