# Generated by Django 4.1.5 on 2023-02-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopkeeper',
            name='shop_id',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254, unique=True),
        ),
    ]
