# Generated by Django 4.1.5 on 2023-02-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_shopkeeper_shop_id_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Li', 'Lifestyles'), ('Ac', 'Accomodation'), ('Tr', 'Transportation'), ('Re', 'Restaurant')], default='Ed', max_length=2)),
                ('name', models.CharField(default='Item name', max_length=100)),
                ('shop_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
