# Generated by Django 4.1.5 on 2023-02-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_item_image_alter_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='desc',
            field=models.CharField(default='Good item', max_length=1000),
        ),
    ]
