# Generated by Django 4.1.5 on 2023-02-14 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='shop_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='shopkeeper_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.shopkeeper'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('W', 'Waiting'), ('D', 'Denied'), ('C', 'Completed')], default='W', max_length=1),
        ),
    ]
