# Generated by Django 4.1.5 on 2023-02-14 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_transaction_shop_id_transaction_shopkeeper_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='shop_id',
            new_name='shopkeeper_id',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='shop_id',
            new_name='shopkeeper_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='shopkeeper',
            name='email_id',
        ),
    ]
