# Generated by Django 4.1.5 on 2023-02-14 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_shop_id_item_shopkeeper_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='service_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.service'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='core.user'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='shopkeeper_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='shopkeeper_id',
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopkeeper_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='core.shopkeeper'),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.customer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='item_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='shopkeeper_id',
            field=models.ManyToManyField(to='core.shopkeeper'),
        ),
        migrations.AddField(
            model_name='service',
            name='shopkeeper_id',
            field=models.ManyToManyField(to='core.shopkeeper'),
        ),
    ]
