# Generated by Django 4.1.5 on 2023-02-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_user_name_item_price_service_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='shopkeeper',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254, unique=True),
        ),
    ]
