# Generated by Django 4.1.5 on 2023-02-16 15:25

import core.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_user_email_customer_email_shopkeeper_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='shopkeeper_id',
            new_name='shopkeeper',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='shopkeeper_id',
            new_name='shopkeeper',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='area_id',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shopkeeper_id',
            new_name='shopkeeper',
        ),
        migrations.RenameField(
            model_name='shopkeeper',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='service_id',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='shopkeeper_id',
            new_name='shopkeeper',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shopkeeper',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='shopkeeper',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shopkeeper',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Login'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='abc', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='abc', help_text='Enter your password', max_length=200),
        ),
    ]
