# Generated by Django 4.1.5 on 2023-02-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_user_email_customer_email_shopkeeper_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shopkeeper',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='shopkeeper',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shopkeeper',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='abc', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='abc', help_text='Enter your password', max_length=200),
        ),
    ]
