# Generated by Django 4.1.5 on 2023-02-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_customer_contact_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images'),
        ),
    ]
