# Generated by Django 4.1.5 on 2023-02-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='shopkeeper',
            field=models.ManyToManyField(related_name='items', to='core.shopkeeper'),
        ),
    ]
