# Generated by Django 4.1.5 on 2023-02-15 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_created_at_user_is_active_user_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
