# Generated by Django 4.1.5 on 2023-02-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='shopkeeper_id',
            new_name='shopkeeper',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='shopkeeper_id',
            new_name='shopkeeper',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='area_id',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shopkeeper_id',
            new_name='shopkeeper',
        ),
        migrations.RenameField(
            model_name='shopkeeper',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='service_id',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='shopkeeper_id',
            new_name='shopkeeper',
        ),
    ]
