# Generated by Django 4.1.5 on 2023-02-15 13:43

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
    ]
